### ISSUE TITLE
Error on npm run build:lib

### ISSUE THREAD

**Issue by isvaljek** [aeneasr/ory-editor#663]
I'm a typescript newbie, and a bit late on the general JS development, so please shed some light on this build error (happens on npm run build:lib):

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ivan/.nvm/versions/node/v10.15.1/bin/node',
1 verbose cli   '/media/ivan/linux-data/dev/plugins/editors/ory/node_modules/.bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.1.0
3 info using node@v10.15.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ory-editor-plugins-html5-video@0.0.0~prebuild: ory-editor-plugins-html5-video@0.0.0
6 verbose lifecycle ory-editor-plugins-html5-video@0.0.0~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle ory-editor-plugins-html5-video@0.0.0~prebuild: PATH: /media/ivan/linux-data/dev/plugins/editors/ory/node_modules/npm/bin/node-gyp-bin:/media/ivan/linux-data/dev/plugins/editors/ory/packages/plugins/content/html5-video/node_modules/.bin:/media/ivan/linux-data/dev/plugins/editors/ory/packages/plugins/content/html5-video/node_modules/.bin:/media/ivan/linux-data/dev/plugins/editors/ory/packages/plugins/content/node_modules/.bin:/media/ivan/linux-data/dev/plugins/editors/ory/packages/plugins/node_modules/.bin:/media/ivan/linux-data/dev/plugins/editors/ory/packages/node_modules/.bin:/media/ivan/linux-data/dev/plugins/editors/ory/node_modules/.bin:/media/ivan/linux-data/dev/plugins/editors/node_modules/.bin:/media/ivan/linux-data/dev/plugins/node_modules/.bin:/media/ivan/linux-data/dev/node_modules/.bin:/media/ivan/linux-data/node_modules/.bin:/media/ivan/node_modules/.bin:/media/node_modules/.bin:/node_modules/.bin:/home/ivan/.nvm/versions/node/v10.15.1/bin:/home/ivan/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/media/ivan/linux-data/dev/plugins/editors/ory/node_modules/.bin:/home/ivan/bin:/home/ivan/.local/bin:/home/ivan/.nvm/versions/node/v10.15.1/bin:/home/ivan/bin:/home/ivan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
8 verbose lifecycle ory-editor-plugins-html5-video@0.0.0~prebuild: CWD: /media/ivan/linux-data/dev/plugins/editors/ory/packages/plugins/content/html5-video
9 silly lifecycle ory-editor-plugins-html5-video@0.0.0~prebuild: Args: [ '-c', 'npm run clean' ]
10 silly lifecycle ory-editor-plugins-html5-video@0.0.0~prebuild: Returned: code: 0  signal: null
11 info lifecycle ory-editor-plugins-html5-video@0.0.0~build: ory-editor-plugins-html5-video@0.0.0
12 verbose lifecycle ory-editor-plugins-html5-video@0.0.0~build: unsafe-perm in lifecycle true
13 verbose lifecycle ory-editor-plugins-html5-video@0.0.0~build: PATH: /media/ivan/linux-data/dev/plugins/editors/ory/node_modules/npm/bin/node-gyp-bin:/media/ivan/linux-data/dev/plugins/editors/ory/packages/plugins/content/html5-video/node_modules/.bin:/media/ivan/linux-data/dev/plugins/editors/ory/packages/plugins/content/html5-video/node_modules/.bin:/media/ivan/linux-data/dev/plugins/editors/ory/packages/plugins/content/node_modules/.bin:/media/ivan/linux-data/dev/plugins/editors/ory/packages/plugins/node_modules/.bin:/media/ivan/linux-data/dev/plugins/editors/ory/packages/node_modules/.bin:/media/ivan/linux-data/dev/plugins/editors/ory/node_modules/.bin:/media/ivan/linux-data/dev/plugins/editors/node_modules/.bin:/media/ivan/linux-data/dev/plugins/node_modules/.bin:/media/ivan/linux-data/dev/node_modules/.bin:/media/ivan/linux-data/node_modules/.bin:/media/ivan/node_modules/.bin:/media/node_modules/.bin:/node_modules/.bin:/home/ivan/.nvm/versions/node/v10.15.1/bin:/home/ivan/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/media/ivan/linux-data/dev/plugins/editors/ory/node_modules/.bin:/home/ivan/bin:/home/ivan/.local/bin:/home/ivan/.nvm/versions/node/v10.15.1/bin:/home/ivan/bin:/home/ivan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
14 verbose lifecycle ory-editor-plugins-html5-video@0.0.0~build: CWD: /media/ivan/linux-data/dev/plugins/editors/ory/packages/plugins/content/html5-video
15 silly lifecycle ory-editor-plugins-html5-video@0.0.0~build: Args: [ '-c', 'npm-run-all --parallel build:lib build:css' ]
16 silly lifecycle ory-editor-plugins-html5-video@0.0.0~build: Returned: code: 1  signal: null
17 info lifecycle ory-editor-plugins-html5-video@0.0.0~build: Failed to exec build script
18 verbose stack Error: ory-editor-plugins-html5-video@0.0.0 build: `npm-run-all --parallel build:lib build:css`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/media/ivan/linux-data/dev/plugins/editors/ory/node_modules/npm/lib/utils/lifecycle.js:289:16)
18 verbose stack     at EventEmitter.emit (events.js:189:13)
18 verbose stack     at ChildProcess.<anonymous> (/media/ivan/linux-data/dev/plugins/editors/ory/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at ChildProcess.emit (events.js:189:13)
18 verbose stack     at maybeClose (internal/child_process.js:970:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
19 verbose pkgid ory-editor-plugins-html5-video@0.0.0
20 verbose cwd /media/ivan/linux-data/dev/plugins/editors/ory/packages/plugins/content/html5-video
21 verbose Linux 4.15.0-46-generic
22 verbose argv "/home/ivan/.nvm/versions/node/v10.15.1/bin/node" "/media/ivan/linux-data/dev/plugins/editors/ory/node_modules/.bin/npm" "run" "build"
23 verbose node v10.15.1
24 verbose npm  v5.1.0
25 error code ELIFECYCLE
26 error errno 1
27 error ory-editor-plugins-html5-video@0.0.0 build: `npm-run-all --parallel build:lib build:css`
27 error Exit status 1
28 error Failed at the ory-editor-plugins-html5-video@0.0.0 build script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]
```

**Comment by isvaljek** [comment]
```
npm run clean:lerna
npm run bootstrap
```
